spring:
  profiles:
    active: local

# local
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true